CREATE TABLE IF NOT EXISTS chat (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  secondUserId INTEGER NOT NULL,
  firstUserId INTEGER NOT NULL,
  FOREIGN KEY (secondUserId) REFERENCES users (id)
  FOREIGN KEY (firstUserId) REFERENCES users (id)
);